export default {
    GET_NOTIFICATIONS: 'GET_NOTIFICATIONS',
    MARK_NOTIFICATION_AS_READ_BY_ID: 'MARK_NOTIFICATION_AS_READ_BY_ID',
    MARK_ALL_NOTIFICATIONS: 'MARK_ALL_NOTIFICATIONS',
    START_NOTIFICATION_LOADING: 'START_NOTIFICATION_LOADING',
    END_NOTIFICATION_LOADING: 'END_NOTIFICATION_LOADING',

    START_SIGN_IN: 'START_SIGN_IN',
    SIGN_IN_SUCCESS : 'SIGN_IN_SUCCESS',
    SIGN_IN_FAIL: 'SIGN_IN_FAIL',
    SIGN_OUT: 'SIGN_OUT',

    START_AVATAR_UPLOAD: 'START_AVATAR_UPLOAD',
    AVATAR_UPLOAD_SUCCESS : 'AVATAR_UPLOAD_SUCCESS',
    AVATAR_UPLOAD_FAILED: 'AVATAR_UPLOAD_FAILED',

    START_GET_USERINFO: 'START_GET_USERINFO',
    GET_USERINFO_SUCCESS : 'GET_USERINFO_SUCCESS',
    GET_USERINFO_FAILED: 'GET_USERINFO_FAILED',

    START_UPDATE_USERINFO: 'START_UPDATE_USERINFO',
    UPDATE_USERINFO_SUCCESS : 'UPDATE_USERINFO_SUCCESS',
    UPDATE_USERINFO_FAILED: 'UPDATE_USERINFO_FAILED',

}